In [1]:
from preprocessor import AzdiasPreprocessor, FeatureDropper
from pprint import pprint
import pandas as pd

In [2]:
preprocessor = AzdiasPreprocessor(
    data_source="Udacity_AZDIAS_Subset.csv",
    summary_source="AZDIAS_Feature_summary.csv",
    na_feature_threshold=20,
    na_sample_threshold=25
)
preprocessor

Loading data from...Udacity_AZDIAS_Subset.csv
No pipeline parameter passed in. Building default pipeline...
Building cleaning pipeline...

In [3]:
# Test One Hot Encoder
df_test = pd.read_csv("Udacity_AZDIAS_Subset.csv", delimiter=";")

In [4]:
df_test.head()

,AGER_TYP,ALTERSKATEGORIE_GROB,ANREDE_KZ,CJT_GESAMTTYP,FINANZ_MINIMALIST,FINANZ_SPARER,FINANZ_VORSORGER,FINANZ_ANLEGER,FINANZ_UNAUFFAELLIGER,FINANZ_HAUSBAUER,...,PLZ8_ANTG1,PLZ8_ANTG2,PLZ8_ANTG3,PLZ8_ANTG4,PLZ8_BAUMAX,PLZ8_HHZ,PLZ8_GBZ,ARBEIT,ORTSGR_KLS9,RELAT_AB
0,-1,2,1,2.0,3,4,3,5,5,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,-1,1,2,5.0,1,5,2,5,4,5,...,2.0,3.0,2.0,1.0,1.0,5.0,4.0,3.0,5.0,4.0
2,-1,3,2,3.0,1,4,1,2,3,5,...,3.0,3.0,1.0,0.0,1.0,4.0,4.0,3.0,5.0,2.0
3,2,4,2,2.0,4,2,5,2,1,2,...,2.0,2.0,2.0,0.0,1.0,3.0,4.0,2.0,3.0,3.0
4,-1,3,1,5.0,4,3,4,1,3,2,...,2.0,4.0,2.0,1.0,2.0,3.0,3.0,4.0,6.0,5.0

In [5]:
df_test = preprocessor.clean_data(df_test)
print(df_test.shape)
df_test.head()

[Pipeline] .. (step 1 of 4) Processing replace_missings, total=   1.8s
Dropping Features: {'GEBURTSJAHR', 'KK_KUNDENTYP', 'TITEL_KZ', 'KBA05_BAUMAX', 'AGER_TYP', 'ALTER_HH'}
Dropped 6 features
[Pipeline] ..... (step 2 of 4) Processing drop_features, total=   0.7s
Kept 797961 rows, dropped 93260 rows
[Pipeline] ........ (step 3 of 4) Processing split_data, total=   0.3s
MixedFeatureEngineer Encoding...
MixedFeatureEngineer Encoded PRAEGENDE_DECADE from PRAEGENDE_JUGENDJAHRE
MixedFeatureEngineer Encoded PRAEGENDE_MOVEMENT from PRAEGENDE_JUGENDJAHRE
MixedFeatureEngineer Encoded CAMEO_WEALTH from CAMEO_INTL_2015
MixedFeatureEngineer Encoded CAMEO_LIFESTAGE from CAMEO_INTL_2015
MixedFeatureEngineer Encoded LP_LIFE_STAGE from LP_LEBENSPHASE_FEIN
MixedFeatureEngineer Encoded LP_INCOME_LEVEL from LP_LEBENSPHASE_FEIN
MixedFeatureEngineer Encoded LP_IS_INDEPENDENT from LP_LEBENSPHASE_FEIN
MixedFeatureEngineer Encoded LP_AGE_CLASS from LP_LEBENSPHASE_FEIN
MixedFeatureEngineer Encoded LP_IS_HOMEOWNER from LP_LEBENSPHASE_FEIN
MixedFeatureEngineer Encoded WOHN_NEIGHBORHOOD_QUALITY from WOHNLAGE
MixedFeatureEngineer Encoded WOHN_IS_RURAL from WOHNLAGE
MixedFeatureEngineer Encoded WOHN_NEW_BUILDING from WOHNLAGE
[Pipeline] .......... (step 4 of 4) Processing engineer, total=   0.9s
(797961, 87)

,ALTERSKATEGORIE_GROB,ANREDE_KZ,CJT_GESAMTTYP,FINANZ_MINIMALIST,FINANZ_SPARER,FINANZ_VORSORGER,FINANZ_ANLEGER,FINANZ_UNAUFFAELLIGER,FINANZ_HAUSBAUER,FINANZTYP,...,PRAEGENDE_MOVEMENT,CAMEO_WEALTH,CAMEO_LIFESTAGE,LP_INCOME_LEVEL,LP_IS_INDEPENDENT,LP_AGE_CLASS,LP_IS_HOMEOWNER,WOHN_NEIGHBORHOOD_QUALITY,WOHN_IS_RURAL,WOHN_NEW_BUILDING
0,1.0,2,5.0,1,5,2,5,4,5,1,...,5.0,1.0,3.0,1.0,NaN,NaN,NaN,4.0,NaN,NaN
1,3.0,2,3.0,1,4,1,2,3,5,1,...,2.0,4.0,1.0,2.0,NaN,1.0,NaN,2.0,NaN,NaN
2,4.0,2,2.0,4,2,5,2,1,2,6,...,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN
3,3.0,1,5.0,4,3,4,1,3,2,5,...,4.0,3.0,5.0,2.0,NaN,3.0,NaN,3.0,NaN,NaN
4,1.0,2,2.0,3,1,5,2,2,5,2,...,5.0,4.0,1.0,2.0,NaN,5.0,NaN,NaN,1.0,NaN