In [1]:
from preprocessor import AzdiasPreprocessor, FeatureDropper
from pprint import pprint
import pandas as pd

import inspect
print(inspect.getsource(AzdiasPreprocessor))

class AzdiasPreprocessor():

    def __init__(
            self,
            data_source,
            summary_source,
            na_feature_threshold=20,
            na_sample_threshold=25,
            cleaning_pipeline=None,
            impute_pipeline=None,
            scaling_pipeline=None,
            split_data=False
    ):
        """
        Initialize the preprocessor.
        :param data_source: path to the general population data file
        :param summary_source: path to the feature summary file
        :param na_feature_threshold: percentage threshold for dropping high-missing features
        :param na_sample_threshold: threshold for splitting population data by row/sample missingness
        :param cleaning_pipeline: custom processing pipeline to apply to the data
        :param impute_pipeline: custom impute pipeline to apply to the data
        :param scaling_pipeline: custom scaling pipeline to apply to the data
        """
        self._data_source = data_source
        self._summary_source = summary_source
        self._na_feature_threshold = na_feature_threshold
        self._na_sample_threshold = na_sample_threshold

        self._feature_groups = {
            BINARY: {
                P_MOVEMENT, LP_HOMEOWN, LP_INDEP, WOHN_RURAL, WOHN_BUILD
            },
            BIN_NO_NUM: set(),
            ORDINAL: {C_WEALTH, C_LIFE, LP_INCOME, LP_AGE, WOHN_QUAL},
            NUMERIC: set(),
            INTERVAL: {P_DECADE},
            MULTI: set(),
            ENGINEERED_FEATURES: {
                P_DECADE, P_MOVEMENT, C_WEALTH, C_LIFE, LP_INCOME,
                LP_INDEP, LP_AGE, LP_HOMEOWN, WOHN_QUAL, WOHN_RURAL,
                WOHN_BUILD
            },
            ENGINEERED_CAT: {LP_STAGE},
            ENCODED_FEATURES: set(),
            TO_ENGINEER: {
                PRA_JUG, CAM_INT, WOHN, LP_LEB
            },
            TO_SCALE: set(),
            TO_DROP: {
                NA_FEATURES: set(),
                OTHER: {
                    "LP_FAMILIE_GROB", "LP_STATUS_GROB", "NATIONALITAET_KZ", "SOHO_KZ",
                    "CAMEO_DEUG_2015", "LP_LEBENSPHASE_GROB", "PLZ8_BAUMAX"
                }
            }
        }

        self._feature_summary = {}
        self._feature_dictionary = {}

        self._load_data()

        if cleaning_pipeline:
            self._cleaning_pipeline = cleaning_pipeline
        else:
            print(f"No pipeline parameter passed in. Building default pipeline...")
            self._cleaning_pipeline = self._build_default_cleaning_pipeline()

        del self._feature_summary

    def _set_na_features_to_drop(self, df):

        replace_missing_transformer = ReplaceMissingTransformer(self._feature_summary)
        replace_missing_transformer.fit_transform(df)
        df = replace_missing_transformer.transform(df)

        df_missing_pct = (df.isna().sum().sort_values() / df.shape[0]) * 100

        self._feature_groups[TO_DROP][NA_FEATURES].update(
            df_missing_pct[df_missing_pct > 20].index.tolist()
        )

        del df_missing_pct
        return df

    def _load_data(self):
        print(f"Loading data from...{self._data_source}")
        df_population_raw = pd.read_csv(self._data_source, delimiter=";")
        self._feature_summary = pd.read_csv(self._summary_source, delimiter=";")

        self._set_feature_groups(df_population_raw)

        del df_population_raw

    def _set_feature_groups(self, df):
        df = self._set_na_features_to_drop(df)

        feature_list =  [
            f for f in df.columns.to_list()
            if f not in self._feature_groups[TO_DROP][NA_FEATURES]
        ]

        ordinal_features = list(
            self._feature_summary[
                (self._feature_summary[FS_ATTR].isin(feature_list)) &
                (self._feature_summary[FS_TYPE] == ORDINAL)][FS_ATTR]
        )

        numerical_features = list(
            self._feature_summary[
                (self._feature_summary[FS_ATTR].isin(feature_list)) &
                (self._feature_summary[FS_TYPE] == NUMERIC)][FS_ATTR]
        )

        self._feature_groups[ORDINAL].update(ordinal_features)
        self._feature_groups[NUMERIC].update(numerical_features)

        categorical_features = list(
            self._feature_summary[
                (self._feature_summary[FS_ATTR].isin(feature_list)) &
                (self._feature_summary[FS_TYPE] == CATEGORICAL)][FS_ATTR]
        )

        # iterate over each categorical
        for feature in categorical_features:

            # skip over the dropped categorical features
            if feature in self._feature_groups[TO_DROP][OTHER]:
                # continue and do not append to any list
                continue

            # check for binary ones
            if df[feature].nunique() == 2:
                # check if numeric or not
                if df[feature].dtype == FS_OBJ:

                    if feature not in self._feature_groups[BIN_NO_NUM]:
                        self._feature_groups[BIN_NO_NUM].add(feature)
                else:
                    if feature not in self._feature_groups[BINARY]:
                        self._feature_groups[BINARY].add(feature)

            # else, it is a multi-level categorical
            else:
                if feature not in self._feature_groups[MULTI]:
                    self._feature_groups[MULTI].add(feature)

    def _build_default_cleaning_pipeline(self):
        print(f"Building cleaning pipeline...")

        # 1. Replace Missings
        replace_missing_transformer = ReplaceMissingTransformer(self._feature_summary)

        # 2. Drop High NaN Features
        drop_na_features_transformer = FeatureDropper(features_to_drop=self._feature_groups[TO_DROP][NA_FEATURES])

        # 3. Split data into two subsets
        splitter = DatasetSplitter(threshold=25)

        # 4. Engineer mixed-type features
        engineer_transformer = MixedFeatureEngineer(mappings=MAPPINGS)

        # 5. Encode Features
        encoder = Encoder(
            ordinal_features=self._feature_groups[ORDINAL],
            onehot_features=self._feature_groups[MULTI]
        )

        pipeline = Pipeline(
            steps=[
                (REPLACE_MISSINGS, replace_missing_transformer),
                (DROP_FEATURES, drop_na_features_transformer),
                # (SPLIT_DATA, splitter),
                #(ENGINEER, engineer_transformer),
                #(ENCODE, encoder)
            ],
            verbose=True
        ).set_output(transform="pandas")

        return pipeline

    def clean_data(self, X):
        X_out = X.copy()

        if self._cleaning_pipeline:
            X_out = self._cleaning_pipeline.fit_transform(X)
        else:
            print(f"No cleaning pipeline provided...returning original data")

        return X_out

In [2]:
preprocessor = AzdiasPreprocessor(
    data_source="Udacity_AZDIAS_Subset.csv",
    summary_source="AZDIAS_Feature_summary.csv",
    na_feature_threshold=20,
    na_sample_threshold=25
)
preprocessor

Loading data from...Udacity_AZDIAS_Subset.csv
No pipeline parameter passed in. Building default pipeline...
Building cleaning pipeline...

In [3]:
pprint(preprocessor._feature_groups)

{'binary': {'ANREDE_KZ',
            'GREEN_AVANTGARDE',
            'LP_IS_HOMEOWNER',
            'LP_IS_INDEPENDENT',
            'PRAEGENDE_MOVEMENT',
            'VERS_TYP',
            'WOHN_IS_RURAL',
            'WOHN_NEW_BUILDING'},
 'encoded_features': set(),
 'engineered_categorical': {'LP_LIFE_STAGE'},
 'engineered_features': {'CAMEO_LIFESTAGE',
                         'CAMEO_WEALTH',
                         'LP_AGE_CLASS',
                         'LP_INCOME_LEVEL',
                         'LP_IS_HOMEOWNER',
                         'LP_IS_INDEPENDENT',
                         'PRAEGENDE_DECADE',
                         'PRAEGENDE_MOVEMENT',
                         'WOHN_IS_RURAL',
                         'WOHN_NEIGHBORHOOD_QUALITY',
                         'WOHN_NEW_BUILDING'},
 'features_to_drop': {'na_features': {'AGER_TYP',
                                      'ALTER_HH',
                                      'GEBURTSJAHR',
                                      'KBA05_BAUMAX',
                                      'KK_KUNDENTYP',
                                      'TITEL_KZ'},
                      'other': {'CAMEO_DEUG_2015',
                                'LP_FAMILIE_GROB',
                                'LP_LEBENSPHASE_GROB',
                                'LP_STATUS_GROB',
                                'NATIONALITAET_KZ',
                                'PLZ8_BAUMAX',
                                'SOHO_KZ'}},
 'features_to_engineer': {'CAMEO_INTL_2015',
                          'LP_LEBENSPHASE_FEIN',
                          'PRAEGENDE_JUGENDJAHRE',
                          'WOHNLAGE'},
 'features_to_scale': set(),
 'interval': {'PRAEGENDE_DECADE'},
 'multi_categorical': {'CAMEO_DEU_2015',
                       'CJT_GESAMTTYP',
                       'FINANZTYP',
                       'GEBAEUDETYP',
                       'GFK_URLAUBERTYP',
                       'LP_FAMILIE_FEIN',
                       'LP_STATUS_FEIN',
                       'SHOPPER_TYP',
                       'ZABEOTYP'},
 'non_numeric_binary': {'OST_WEST_KZ'},
 'numeric': {'ANZ_HAUSHALTE_AKTIV',
             'ANZ_HH_TITEL',
             'ANZ_PERSONEN',
             'ANZ_TITEL',
             'KBA13_ANZAHL_PKW',
             'MIN_GEBAEUDEJAHR'},
 'ordinal': {'ALTERSKATEGORIE_GROB',
             'ARBEIT',
             'BALLRAUM',
             'CAMEO_LIFESTAGE',
             'CAMEO_WEALTH',
             'EWDICHTE',
             'FINANZ_ANLEGER',
             'FINANZ_HAUSBAUER',
             'FINANZ_MINIMALIST',
             'FINANZ_SPARER',
             'FINANZ_UNAUFFAELLIGER',
             'FINANZ_VORSORGER',
             'GEBAEUDETYP_RASTER',
             'HEALTH_TYP',
             'HH_EINKOMMEN_SCORE',
             'INNENSTADT',
             'KBA05_ANTG1',
             'KBA05_ANTG2',
             'KBA05_ANTG3',
             'KBA05_ANTG4',
             'KBA05_GBZ',
             'KKK',
             'KONSUMNAEHE',
             'LP_AGE_CLASS',
             'LP_INCOME_LEVEL',
             'MOBI_REGIO',
             'ONLINE_AFFINITAET',
             'ORTSGR_KLS9',
             'PLZ8_ANTG1',
             'PLZ8_ANTG2',
             'PLZ8_ANTG3',
             'PLZ8_ANTG4',
             'PLZ8_GBZ',
             'PLZ8_HHZ',
             'REGIOTYP',
             'RELAT_AB',
             'RETOURTYP_BK_S',
             'SEMIO_DOM',
             'SEMIO_ERL',
             'SEMIO_FAM',
             'SEMIO_KAEM',
             'SEMIO_KRIT',
             'SEMIO_KULT',
             'SEMIO_LUST',
             'SEMIO_MAT',
             'SEMIO_PFLICHT',
             'SEMIO_RAT',
             'SEMIO_REL',
             'SEMIO_SOZ',
             'SEMIO_TRADV',
             'SEMIO_VERT',
             'WOHNDAUER_2008',
             'WOHN_NEIGHBORHOOD_QUALITY',
             'W_KEIT_KIND_HH'}}

In [4]:
# Test One Hot Encoder
df_test = pd.read_csv("Udacity_AZDIAS_Subset.csv", delimiter=";")

In [5]:
df_test.head()

,AGER_TYP,ALTERSKATEGORIE_GROB,ANREDE_KZ,CJT_GESAMTTYP,FINANZ_MINIMALIST,FINANZ_SPARER,FINANZ_VORSORGER,FINANZ_ANLEGER,FINANZ_UNAUFFAELLIGER,FINANZ_HAUSBAUER,...,PLZ8_ANTG1,PLZ8_ANTG2,PLZ8_ANTG3,PLZ8_ANTG4,PLZ8_BAUMAX,PLZ8_HHZ,PLZ8_GBZ,ARBEIT,ORTSGR_KLS9,RELAT_AB
0,-1,2,1,2.0,3,4,3,5,5,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,-1,1,2,5.0,1,5,2,5,4,5,...,2.0,3.0,2.0,1.0,1.0,5.0,4.0,3.0,5.0,4.0
2,-1,3,2,3.0,1,4,1,2,3,5,...,3.0,3.0,1.0,0.0,1.0,4.0,4.0,3.0,5.0,2.0
3,2,4,2,2.0,4,2,5,2,1,2,...,2.0,2.0,2.0,0.0,1.0,3.0,4.0,2.0,3.0,3.0
4,-1,3,1,5.0,4,3,4,1,3,2,...,2.0,4.0,2.0,1.0,2.0,3.0,3.0,4.0,6.0,5.0

In [6]:
df_test = preprocessor.clean_data(df_test)
df_test.head()

[Pipeline] .. (step 1 of 2) Processing replace_missings, total=   1.8s
Dropping Features: {'ALTER_HH', 'AGER_TYP', 'KBA05_BAUMAX', 'GEBURTSJAHR', 'TITEL_KZ', 'KK_KUNDENTYP'}
Dropped 6 features
Dropped Features: ['ALTER_HH', 'AGER_TYP', 'KBA05_BAUMAX', 'GEBURTSJAHR', 'TITEL_KZ', 'KK_KUNDENTYP']
get_feature_names_out: ['ALTERSKATEGORIE_GROB', 'ANREDE_KZ', 'CJT_GESAMTTYP', 'FINANZ_MINIMALIST', 'FINANZ_SPARER', 'FINANZ_VORSORGER', 'FINANZ_ANLEGER', 'FINANZ_UNAUFFAELLIGER', 'FINANZ_HAUSBAUER', 'FINANZTYP', 'GFK_URLAUBERTYP', 'GREEN_AVANTGARDE', 'HEALTH_TYP', 'LP_LEBENSPHASE_FEIN', 'LP_LEBENSPHASE_GROB', 'LP_FAMILIE_FEIN', 'LP_FAMILIE_GROB', 'LP_STATUS_FEIN', 'LP_STATUS_GROB', 'NATIONALITAET_KZ', 'PRAEGENDE_JUGENDJAHRE', 'RETOURTYP_BK_S', 'SEMIO_SOZ', 'SEMIO_FAM', 'SEMIO_REL', 'SEMIO_MAT', 'SEMIO_VERT', 'SEMIO_LUST', 'SEMIO_ERL', 'SEMIO_KULT', 'SEMIO_RAT', 'SEMIO_KRIT', 'SEMIO_DOM', 'SEMIO_KAEM', 'SEMIO_PFLICHT', 'SEMIO_TRADV', 'SHOPPER_TYP', 'SOHO_KZ', 'VERS_TYP', 'ZABEOTYP', 'ANZ_PERSONEN', 'ANZ_TITEL', 'HH_EINKOMMEN_SCORE', 'W_KEIT_KIND_HH', 'WOHNDAUER_2008', 'ANZ_HAUSHALTE_AKTIV', 'ANZ_HH_TITEL', 'GEBAEUDETYP', 'KONSUMNAEHE', 'MIN_GEBAEUDEJAHR', 'OST_WEST_KZ', 'WOHNLAGE', 'CAMEO_DEUG_2015', 'CAMEO_DEU_2015', 'CAMEO_INTL_2015', 'KBA05_ANTG1', 'KBA05_ANTG2', 'KBA05_ANTG3', 'KBA05_ANTG4', 'KBA05_GBZ', 'BALLRAUM', 'EWDICHTE', 'INNENSTADT', 'GEBAEUDETYP_RASTER', 'KKK', 'MOBI_REGIO', 'ONLINE_AFFINITAET', 'REGIOTYP', 'KBA13_ANZAHL_PKW', 'PLZ8_ANTG1', 'PLZ8_ANTG2', 'PLZ8_ANTG3', 'PLZ8_ANTG4', 'PLZ8_BAUMAX', 'PLZ8_HHZ', 'PLZ8_GBZ', 'ARBEIT', 'ORTSGR_KLS9', 'RELAT_AB']
get_feature_names_out length: 79
Dropped Features: ['ALTER_HH', 'AGER_TYP', 'KBA05_BAUMAX', 'GEBURTSJAHR', 'TITEL_KZ', 'KK_KUNDENTYP']
get_feature_names_out: ['ALTERSKATEGORIE_GROB', 'ANREDE_KZ', 'CJT_GESAMTTYP', 'FINANZ_MINIMALIST', 'FINANZ_SPARER', 'FINANZ_VORSORGER', 'FINANZ_ANLEGER', 'FINANZ_UNAUFFAELLIGER', 'FINANZ_HAUSBAUER', 'FINANZTYP', 'GFK_URLAUBERTYP', 'GREEN_AVANTGARDE', 'HEALTH_TYP', 'LP_LEBENSPHASE_FEIN', 'LP_LEBENSPHASE_GROB', 'LP_FAMILIE_FEIN', 'LP_FAMILIE_GROB', 'LP_STATUS_FEIN', 'LP_STATUS_GROB', 'NATIONALITAET_KZ', 'PRAEGENDE_JUGENDJAHRE', 'RETOURTYP_BK_S', 'SEMIO_SOZ', 'SEMIO_FAM', 'SEMIO_REL', 'SEMIO_MAT', 'SEMIO_VERT', 'SEMIO_LUST', 'SEMIO_ERL', 'SEMIO_KULT', 'SEMIO_RAT', 'SEMIO_KRIT', 'SEMIO_DOM', 'SEMIO_KAEM', 'SEMIO_PFLICHT', 'SEMIO_TRADV', 'SHOPPER_TYP', 'SOHO_KZ', 'VERS_TYP', 'ZABEOTYP', 'ANZ_PERSONEN', 'ANZ_TITEL', 'HH_EINKOMMEN_SCORE', 'W_KEIT_KIND_HH', 'WOHNDAUER_2008', 'ANZ_HAUSHALTE_AKTIV', 'ANZ_HH_TITEL', 'GEBAEUDETYP', 'KONSUMNAEHE', 'MIN_GEBAEUDEJAHR', 'OST_WEST_KZ', 'WOHNLAGE', 'CAMEO_DEUG_2015', 'CAMEO_DEU_2015', 'CAMEO_INTL_2015', 'KBA05_ANTG1', 'KBA05_ANTG2', 'KBA05_ANTG3', 'KBA05_ANTG4', 'KBA05_GBZ', 'BALLRAUM', 'EWDICHTE', 'INNENSTADT', 'GEBAEUDETYP_RASTER', 'KKK', 'MOBI_REGIO', 'ONLINE_AFFINITAET', 'REGIOTYP', 'KBA13_ANZAHL_PKW', 'PLZ8_ANTG1', 'PLZ8_ANTG2', 'PLZ8_ANTG3', 'PLZ8_ANTG4', 'PLZ8_BAUMAX', 'PLZ8_HHZ', 'PLZ8_GBZ', 'ARBEIT', 'ORTSGR_KLS9', 'RELAT_AB']
get_feature_names_out length: 79
[Pipeline] ..... (step 2 of 2) Processing drop_features, total=   0.7s

,ALTERSKATEGORIE_GROB,ANREDE_KZ,CJT_GESAMTTYP,FINANZ_MINIMALIST,FINANZ_SPARER,FINANZ_VORSORGER,FINANZ_ANLEGER,FINANZ_UNAUFFAELLIGER,FINANZ_HAUSBAUER,FINANZTYP,...,PLZ8_ANTG1,PLZ8_ANTG2,PLZ8_ANTG3,PLZ8_ANTG4,PLZ8_BAUMAX,PLZ8_HHZ,PLZ8_GBZ,ARBEIT,ORTSGR_KLS9,RELAT_AB
0,2.0,1,2.0,3,4,3,5,5,3,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1.0,2,5.0,1,5,2,5,4,5,1,...,2.0,3.0,2.0,1.0,1.0,5.0,4.0,3.0,5.0,4.0
2,3.0,2,3.0,1,4,1,2,3,5,1,...,3.0,3.0,1.0,0.0,1.0,4.0,4.0,3.0,5.0,2.0
3,4.0,2,2.0,4,2,5,2,1,2,6,...,2.0,2.0,2.0,0.0,1.0,3.0,4.0,2.0,3.0,3.0
4,3.0,1,5.0,4,3,4,1,3,2,5,...,2.0,4.0,2.0,1.0,2.0,3.0,3.0,4.0,6.0,5.0