In [1]:
from preprocessor import AzdiasPreprocessor, FeatureDropper, Encoder
from pprint import pprint
import pandas as pd

In [2]:
# preprocessor = AzdiasPreprocessor(
#     data_source="Udacity_AZDIAS_Subset.csv",
#     summary_source="AZDIAS_Feature_summary.csv",
#     na_feature_threshold=20,
#     na_sample_threshold=25
# )
# preprocessor

In [3]:
# Test One Hot Encoder
df_test_raw = pd.read_csv("Udacity_AZDIAS_Subset.csv", delimiter=";")

In [4]:
df_test_raw.head()

,AGER_TYP,ALTERSKATEGORIE_GROB,ANREDE_KZ,CJT_GESAMTTYP,FINANZ_MINIMALIST,FINANZ_SPARER,FINANZ_VORSORGER,FINANZ_ANLEGER,FINANZ_UNAUFFAELLIGER,FINANZ_HAUSBAUER,...,PLZ8_ANTG1,PLZ8_ANTG2,PLZ8_ANTG3,PLZ8_ANTG4,PLZ8_BAUMAX,PLZ8_HHZ,PLZ8_GBZ,ARBEIT,ORTSGR_KLS9,RELAT_AB
0,-1,2,1,2.0,3,4,3,5,5,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,-1,1,2,5.0,1,5,2,5,4,5,...,2.0,3.0,2.0,1.0,1.0,5.0,4.0,3.0,5.0,4.0
2,-1,3,2,3.0,1,4,1,2,3,5,...,3.0,3.0,1.0,0.0,1.0,4.0,4.0,3.0,5.0,2.0
3,2,4,2,2.0,4,2,5,2,1,2,...,2.0,2.0,2.0,0.0,1.0,3.0,4.0,2.0,3.0,3.0
4,-1,3,1,5.0,4,3,4,1,3,2,...,2.0,4.0,2.0,1.0,2.0,3.0,3.0,4.0,6.0,5.0

In [5]:
# df_test_1 = preprocessor.clean_data(df_test_raw)
# df_test_1.head()

In [6]:
df_test_ost = df_test_raw[['OST_WEST_KZ']]
df_test_ost.head()

  OST_WEST_KZ
0         NaN
1           W
2           W
3           W
4           W

In [7]:
ordinal_encoder = Encoder(
    ordinal_features=['OST_WEST_KZ'],
    onehot_features=[],
)

In [8]:
df_test_raw['OST_WEST_KZ'].value_counts()

OST_WEST_KZ
W    629528
O    168545
Name: count, dtype: int64

In [9]:
df_test_ost.value_counts()

OST_WEST_KZ
W              629528
O              168545
Name: count, dtype: int64

In [10]:
type(df_test_ost)
df_test_ost.head()

  OST_WEST_KZ
0         NaN
1           W
2           W
3           W
4           W

In [11]:
df_test_ost = ordinal_encoder.fit_transform(df_test_ost)
df_test_ost.head()

Encoder Fitting Ordinal Encoder...
onehot_features: []
ordinal_features: ['OST_WEST_KZ']
Encoder Creating and Fitting Ordinal Encoder...
Encoder Engineering Features...
Ordinal encoded 1 feature(s)
One-hot encoded 0 feature(s) into 0 features

   OST_WEST_KZ
0          NaN
1          1.0
2          1.0
3          1.0
4          1.0

In [12]:
df_test_ost.value_counts()

OST_WEST_KZ
1.0            629528
0.0            168545
Name: count, dtype: int64

In [32]:
df_test_onehot = df_test_raw[['CAMEO_DEU_2015']]
print(df_test_onehot.shape)
df_test_onehot.head()

(891221, 1)

  CAMEO_DEU_2015
0            NaN
1             8A
2             4C
3             2A
4             6B

In [33]:
print(f"df_test_onehot unique: {df_test_onehot['CAMEO_DEU_2015'].unique()}")
print(f"df_test_onehot count unique: {df_test_onehot['CAMEO_DEU_2015'].nunique()}")
print(df_test_onehot.isna().sum())
df_test_onehot.value_counts().sort_index()

df_test_onehot unique: [nan '8A' '4C' '2A' '6B' '8C' '4A' '2D' '1A' '1E' '9D' '5C' '8B' '7A' '5D'
 '9E' '9B' '1B' '3D' '4E' '4B' '3C' '5A' '7B' '9A' '6D' '6E' '2C' '7C'
 '9C' '7D' '5E' '1D' '8D' '6C' '6A' '5B' '4D' '3A' '2B' '7E' '3B' '6F'
 '5F' '1C' 'XX']
df_test_onehot count unique: 45
CAMEO_DEU_2015    98979
dtype: int64

CAMEO_DEU_2015
1A                10850
1B                 4071
1C                 4317
1D                11909
1E                 5065
2A                13249
2B                15486
2C                19422
2D                35074
3A                10543
3B                 7160
3C                34769
3D                34307
4A                33155
4B                 9047
4C                47819
4D                 8570
4E                 5321
5A                12214
5B                10354
5C                 9935
5D                14943
5E                 3581
5F                 4283
6A                 6810
6B                56672
6C                14820
6D                 6073
6E                16107
6F                 5392
7A                34399
7B                24503
7C                 9065
7D                 5333
7E                 4633
8A                52438
8B                33434
8C                30993
8D                17576
9A                20542
9B                27676
9C                24987
9D                28593
9E                 6379
XX                  373
Name: count, dtype: int64

In [21]:
onehot_encoder = Encoder(
    ordinal_features= [],
    onehot_features=['CAMEO_DEU_2015'],
)
onehot_encoder

Encoder(onehot_features=['CAMEO_DEU_2015'], ordinal_features=[])

In [30]:
df_test_onehot = onehot_encoder.fit_transform(df_test_onehot)
df_test_onehot.head()

Encoder Fitting Ordinal Encoder...
onehot_features: ['CAMEO_DEU_2015']
ordinal_features: []
Encoder Creating and Fitting Onehot Encoder...
Encoder Engineering Features...
Ordinal encoded 0 feature(s)
One-hot encoded 1 feature(s) into 46 features

,CAMEO_DEU_2015_1A,CAMEO_DEU_2015_1B,CAMEO_DEU_2015_1C,CAMEO_DEU_2015_1D,CAMEO_DEU_2015_1E,CAMEO_DEU_2015_2A,CAMEO_DEU_2015_2B,CAMEO_DEU_2015_2C,CAMEO_DEU_2015_2D,CAMEO_DEU_2015_3A,...,CAMEO_DEU_2015_8B,CAMEO_DEU_2015_8C,CAMEO_DEU_2015_8D,CAMEO_DEU_2015_9A,CAMEO_DEU_2015_9B,CAMEO_DEU_2015_9C,CAMEO_DEU_2015_9D,CAMEO_DEU_2015_9E,CAMEO_DEU_2015_XX,CAMEO_DEU_2015_nan
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [31]:
df_test_onehot.sum()

CAMEO_DEU_2015_1A     10850.0
CAMEO_DEU_2015_1B      4071.0
CAMEO_DEU_2015_1C      4317.0
CAMEO_DEU_2015_1D     11909.0
CAMEO_DEU_2015_1E      5065.0
CAMEO_DEU_2015_2A     13249.0
CAMEO_DEU_2015_2B     15486.0
CAMEO_DEU_2015_2C     19422.0
CAMEO_DEU_2015_2D     35074.0
CAMEO_DEU_2015_3A     10543.0
CAMEO_DEU_2015_3B      7160.0
CAMEO_DEU_2015_3C     34769.0
CAMEO_DEU_2015_3D     34307.0
CAMEO_DEU_2015_4A     33155.0
CAMEO_DEU_2015_4B      9047.0
CAMEO_DEU_2015_4C     47819.0
CAMEO_DEU_2015_4D      8570.0
CAMEO_DEU_2015_4E      5321.0
CAMEO_DEU_2015_5A     12214.0
CAMEO_DEU_2015_5B     10354.0
CAMEO_DEU_2015_5C      9935.0
CAMEO_DEU_2015_5D     14943.0
CAMEO_DEU_2015_5E      3581.0
CAMEO_DEU_2015_5F      4283.0
CAMEO_DEU_2015_6A      6810.0
CAMEO_DEU_2015_6B     56672.0
CAMEO_DEU_2015_6C     14820.0
CAMEO_DEU_2015_6D      6073.0
CAMEO_DEU_2015_6E     16107.0
CAMEO_DEU_2015_6F      5392.0
CAMEO_DEU_2015_7A     34399.0
CAMEO_DEU_2015_7B     24503.0
CAMEO_DEU_2015_7C      9065.0
CAMEO_DEU_2015_7D      5333.0
CAMEO_DEU_2015_7E      4633.0
CAMEO_DEU_2015_8A     52438.0
CAMEO_DEU_2015_8B     33434.0
CAMEO_DEU_2015_8C     30993.0
CAMEO_DEU_2015_8D     17576.0
CAMEO_DEU_2015_9A     20542.0
CAMEO_DEU_2015_9B     27676.0
CAMEO_DEU_2015_9C     24987.0
CAMEO_DEU_2015_9D     28593.0
CAMEO_DEU_2015_9E      6379.0
CAMEO_DEU_2015_XX       373.0
CAMEO_DEU_2015_nan    98979.0
dtype: float64