In [1]:
from preprocessor import AzdiasPreprocessor, FeatureDropper
from pprint import pprint
import pandas as pd

In [2]:
preprocessor = AzdiasPreprocessor(
    data_source="Udacity_AZDIAS_Subset.csv",
    summary_source="AZDIAS_Feature_summary.csv",
    na_feature_threshold=20,
    na_sample_threshold=25
)
preprocessor

Loading data from...Udacity_AZDIAS_Subset.csv
No pipeline parameter passed in. Building default pipeline...
Building cleaning pipeline...
No impute and scale pipeline parameter passed in. Building default pipeline...
Building imputation and scaling pipeline...

In [3]:
# Test One Hot Encoder
df_test = pd.read_csv("Udacity_AZDIAS_Subset.csv", delimiter=";")

In [4]:
df_test.head()

,AGER_TYP,ALTERSKATEGORIE_GROB,ANREDE_KZ,CJT_GESAMTTYP,FINANZ_MINIMALIST,FINANZ_SPARER,FINANZ_VORSORGER,FINANZ_ANLEGER,FINANZ_UNAUFFAELLIGER,FINANZ_HAUSBAUER,...,PLZ8_ANTG1,PLZ8_ANTG2,PLZ8_ANTG3,PLZ8_ANTG4,PLZ8_BAUMAX,PLZ8_HHZ,PLZ8_GBZ,ARBEIT,ORTSGR_KLS9,RELAT_AB
0,-1,2,1,2.0,3,4,3,5,5,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,-1,1,2,5.0,1,5,2,5,4,5,...,2.0,3.0,2.0,1.0,1.0,5.0,4.0,3.0,5.0,4.0
2,-1,3,2,3.0,1,4,1,2,3,5,...,3.0,3.0,1.0,0.0,1.0,4.0,4.0,3.0,5.0,2.0
3,2,4,2,2.0,4,2,5,2,1,2,...,2.0,2.0,2.0,0.0,1.0,3.0,4.0,2.0,3.0,3.0
4,-1,3,1,5.0,4,3,4,1,3,2,...,2.0,4.0,2.0,1.0,2.0,3.0,3.0,4.0,6.0,5.0

In [5]:
df_test = preprocessor.clean_data(df_test)
print(df_test.shape)
df_test.head()

Cleaning data...
[Pipeline] .. (step 1 of 6) Processing replace_missings, total=   1.8s
Dropping Features: ['AGER_TYP', 'KBA05_BAUMAX', 'KK_KUNDENTYP', 'ALTER_HH', 'TITEL_KZ', 'GEBURTSJAHR']
Dropped 6 features
[Pipeline] ..... (step 2 of 6) Processing drop_features, total=   0.7s
Kept 797961 rows, dropped 93260 rows
[Pipeline] ........ (step 3 of 6) Processing split_data, total=   0.3s
Dropping Features: ['SOHO_KZ', 'LP_LEBENSPHASE_GROB', 'CAMEO_DEUG_2015', 'NATIONALITAET_KZ', 'LP_STATUS_GROB', 'PLZ8_BAUMAX', 'LP_FAMILIE_GROB']
Dropped 7 features
[Pipeline] .. (step 4 of 6) Processing drop_categorical, total=   0.5s
MixedFeatureEngineer Encoding...
MixedFeatureEngineer Encoded PRAEGENDE_DECADE from PRAEGENDE_JUGENDJAHRE
MixedFeatureEngineer Encoded PRAEGENDE_MOVEMENT from PRAEGENDE_JUGENDJAHRE
MixedFeatureEngineer Dropped PRAEGENDE_JUGENDJAHRE
MixedFeatureEngineer Encoded CAMEO_WEALTH from CAMEO_INTL_2015
MixedFeatureEngineer Encoded CAMEO_LIFESTAGE from CAMEO_INTL_2015
MixedFeatureEngineer Dropped CAMEO_INTL_2015
MixedFeatureEngineer Encoded LP_LIFE_STAGE from LP_LEBENSPHASE_FEIN
MixedFeatureEngineer Encoded LP_INCOME_LEVEL from LP_LEBENSPHASE_FEIN
MixedFeatureEngineer Encoded LP_IS_INDEPENDENT from LP_LEBENSPHASE_FEIN
MixedFeatureEngineer Encoded LP_AGE_CLASS from LP_LEBENSPHASE_FEIN
MixedFeatureEngineer Encoded LP_IS_HOMEOWNER from LP_LEBENSPHASE_FEIN
MixedFeatureEngineer Dropped LP_LEBENSPHASE_FEIN
MixedFeatureEngineer Encoded WOHN_NEIGHBORHOOD_QUALITY from WOHNLAGE
MixedFeatureEngineer Encoded WOHN_IS_RURAL from WOHNLAGE
MixedFeatureEngineer Encoded WOHN_NEW_BUILDING from WOHNLAGE
MixedFeatureEngineer Dropped WOHNLAGE
[Pipeline] .......... (step 5 of 6) Processing engineer, total=   0.8s
Encoder Creating and Fitting Ordinal Encoder...
Encoder Creating and Fitting Onehot Encoder...
Encoder Engineering Features...
Ordinal encoded 1 feature(s)
One-hot encoded 10 feature(s) into 118 features
[Pipeline] ............ (step 6 of 6) Processing encode, total=   1.2s
(797961, 188)

,ALTERSKATEGORIE_GROB,ANREDE_KZ,FINANZ_MINIMALIST,FINANZ_SPARER,FINANZ_VORSORGER,FINANZ_ANLEGER,FINANZ_UNAUFFAELLIGER,FINANZ_HAUSBAUER,GREEN_AVANTGARDE,HEALTH_TYP,...,CAMEO_DEU_2015_8A,CAMEO_DEU_2015_8B,CAMEO_DEU_2015_8C,CAMEO_DEU_2015_8D,CAMEO_DEU_2015_9A,CAMEO_DEU_2015_9B,CAMEO_DEU_2015_9C,CAMEO_DEU_2015_9D,CAMEO_DEU_2015_9E,CAMEO_DEU_2015_nan
0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,5.0,1.0,3.0,1.0,NaN,NaN,4.0,NaN,NaN
1,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,2.0,4.0,1.0,2.0,NaN,NaN,2.0,NaN,NaN
2,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,1.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN
3,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,...,1.0,4.0,3.0,5.0,2.0,NaN,NaN,3.0,NaN,NaN
4,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,5.0,4.0,1.0,2.0,NaN,NaN,NaN,1.0,NaN

In [6]:
scale_pipeline = preprocessor.scale_pipeline
scale_pipeline

Pipeline not fitted yet. Returning unfitted pipeline...

StandardScaler()

In [7]:
impute_pipeline = preprocessor.impute_pipeline
impute_pipeline

Pipeline not fitted yet. Returning unfitted pipeline...

ColumnTransformer(remainder='passthrough',
                  transformers=[('binary',
                                 SimpleImputer(strategy='most_frequent'),
                                 ['WOHN_NEW_BUILDING', 'ANREDE_KZ',
                                  'GREEN_AVANTGARDE', 'LP_IS_HOMEOWNER',
                                  'WOHN_IS_RURAL', 'PRAEGENDE_MOVEMENT',
                                  'LP_IS_INDEPENDENT', 'VERS_TYP']),
                                ('non_numeric_binary',
                                 SimpleImputer(strategy='most_frequent'),
                                 ['OST_WEST_KZ']),
                                ('ordinal', SimpleImputer(...
                                  'W_KEIT_KIND_HH', 'ALTERSKATEGORIE_GROB',
                                  'CAMEO_LIFESTAGE', 'ORTSGR_KLS9',
                                  'MOBI_REGIO', 'KONSUMNAEHE', ...]),
                                ('numeric', SimpleImputer(strategy='median'),
                                 ['ANZ_PERSONEN', 'ANZ_HAUSHALTE_AKTIV',
                                  'MIN_GEBAEUDEJAHR', 'ANZ_TITEL',
                                  'ANZ_HH_TITEL', 'KBA13_ANZAHL_PKW']),
                                ('interval', SimpleImputer(strategy='median'),
                                 ['PRAEGENDE_DECADE'])],
                  verbose_feature_names_out=False)

In [8]:
df_test = preprocessor.impute_and_scale_data(df_test)
df_test.head()

Imputing and Scaling data...
[Pipeline] ............ (step 1 of 2) Processing impute, total=   2.2s
[Pipeline] ............. (step 2 of 2) Processing scale, total=   2.0s
Data has been imputed and scaled

,WOHN_NEW_BUILDING,ANREDE_KZ,GREEN_AVANTGARDE,LP_IS_HOMEOWNER,WOHN_IS_RURAL,PRAEGENDE_MOVEMENT,LP_IS_INDEPENDENT,VERS_TYP,OST_WEST_KZ,LP_INCOME_LEVEL,...,CAMEO_DEU_2015_8A,CAMEO_DEU_2015_8B,CAMEO_DEU_2015_8C,CAMEO_DEU_2015_8D,CAMEO_DEU_2015_9A,CAMEO_DEU_2015_9B,CAMEO_DEU_2015_9C,CAMEO_DEU_2015_9D,CAMEO_DEU_2015_9E,CAMEO_DEU_2015_nan
0,-0.158582,1.745851,-0.307072,-0.121318,-0.103924,-0.001119,-0.375374,-0.108023,-0.167513,-1.008959,...,0.543109,1.186667,-1.261487,0.358493,-0.745650,NaN,NaN,0.784228,NaN,NaN
1,-0.158582,1.745851,-0.307072,-0.121318,-0.103924,-0.001119,-0.375374,-0.108023,-0.167513,0.991120,...,-1.841251,-0.861823,0.759023,-0.816868,-0.067472,NaN,NaN,-1.082095,NaN,NaN
2,-0.158582,-0.572787,-0.307072,-0.121318,-0.103924,-0.001119,-0.375374,-0.108023,-0.167513,-1.008959,...,0.543109,-1.544653,-0.587983,NaN,NaN,NaN,NaN,NaN,0.0,NaN
3,-0.158582,-0.572787,-0.307072,-0.121318,-0.103924,-0.001119,-0.375374,-0.108023,-0.167513,-1.008959,...,0.543109,0.503837,0.085520,1.533853,-0.067472,NaN,NaN,-0.148934,NaN,NaN
4,-0.158582,-0.572787,-0.307072,-0.121318,-0.103924,-0.001119,-0.375374,-0.108023,-0.167513,0.991120,...,0.543109,1.186667,0.759023,-0.816868,-0.067472,NaN,NaN,NaN,0.0,NaN

In [11]:
df_test.describe().mean(axis=1)

count    7.766230e+05
mean    -1.785764e-16
std      9.787240e-01
min     -7.298304e-01
25%     -4.258241e-01
50%     -1.380079e-01
75%      1.546768e-01
max      1.039041e+01
dtype: float64